# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/auth/*.proto --go_out=./internal/proto/ --go_opt=paths=source_relative --go-grpc_out=./internal/proto/ --go-grpc_opt=paths=source_relative
