# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - g
    desc: "Generate code from proto files"
    cmds:
      - protoc -I pkg pkg/proto/**/*.proto --go_out=./internal/pkg/ --go_opt=paths=source_relative --go-grpc_out=./internal/pkg/ --go-grpc_opt=paths=source_relative

  build:
    aliases:
      - b
    desc: "Builds the application via Docker"
    cmds:
      - docker-compose -f deployments/docker-compose.yaml --env-file=".env" up -d

  rebuild:
    aliases:
      - rb
    desc: "Rebuilds the application via Docker"
    cmds:
      - docker-compose -f deployments/docker-compose.yaml --env-file=".env" up -d --build
